article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name= "article"

urlpatterns=[
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from article import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('elektrik/', views.elektrik, name="elektrik"),
    path('yazilim/', views.yazilim, name="yazilim"),
    path('mekanik/', views.mekanik, name="mekanik"),
    path('contact/', views.contact, name="contact"),
    path('contact/help', views.addHelp, name="help"),
    path('articles/',include("article.urls"))   ,
    path('user/',include("user.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    article_aciklama=models.CharField(default="Açıklamalar Burada Görünür",max_length=50)
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name ="Yazar")
    title = models.CharField(max_length = 50,default="Başlık")
       
    
    content = RichTextField()
    
    created_date = models.DateTimeField(auto_now_add= True,verbose_name="Oluşturulma Tarihi") 
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article= models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author=models.CharField(max_length=50,verbose_name="İsim")
    comment_content=models.CharField(max_length=200,verbose_name="Yorum")
    comment_date=models.DateTimeField(auto_now_add=True)
    comment_oy=models.CharField(max_length=50,default="Oy",blank=False,null=False)
    comment_script=models.CharField(max_length=100,default=" ")
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

class help(models.Model):
    article= models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale", blank=True, null=True)
    help_name=models.CharField(default="isim",max_length=50)
    help_mail=models.EmailField(default="Email",max_length=50)
    help_date=models.DateField(auto_now_add=True)
    help_title=models.CharField(default="konu",max_length=50)
    help_content=models.TextField(default="Sizi dinliyoruz",max_length=500)
    
    
    
    
    def __str__(self):
        return self.help_content

    class Meta:
        ordering = ['-help_date']



class Product(models.Model):
    prohelp=models.CharField(default="Buraya bir uyarı bırak.(Sadece sen göreceksin)",max_length=50)
    title = models.CharField(max_length = 50,default="Ürün Adı")
    pro_content = RichTextField()
    pro_date=models.DateTimeField(auto_now_add=True)
    pro_image = models.FileField(blank = True,null = True,verbose_name="Bir fotoğraf ekle. (Unidecimal 180*180 boyutları tavsiye ediyor)")
    def __str__(self):
        return self.pro_content

    class Meta:
        ordering = ['pro_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["content","article_image"]

    

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment,Product,help
from django.contrib.auth.decorators import login_required 

# Create your views here.

def contact(request):
    ic_cont1=Article.objects.get(title="ic_cont1")
    ic_cont2=Article.objects.get(title="ic_cont2")
    
    return render(request,"contact.html",{"ic_cont1":ic_cont1,"ic_cont2":ic_cont2})



def articles(request):
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def index(request):
    
    products= Product.objects.all()
    comments = Comment.objects.all()

    ic_an1=Article.objects.get(title="ic_an1")
    ic_an2=Article.objects.get(title="ic_an2")
    ic_an3=Article.objects.get(title="ic_an3")
    ic_an4=Article.objects.get(title="ic_an4")
    nasilcalisiyoruz=Article.objects.get(title="nasilcalisiyoruz")
    return render(request,"index.html", {"products":products,"comments":comments,"ic_an1":ic_an1,"ic_an2":ic_an2,"ic_an3":ic_an3,"ic_an4":ic_an4, "nasilcalisiyoruz":nasilcalisiyoruz })

def elektrik(request):

    products= Product.objects.all()
    comments = Comment.objects.all()

    elektrik_an1=Article.objects.get(title="elektrik_an1")
    elektrik_an2=Article.objects.get(title="elektrik_an2")
    elektrik_an3=Article.objects.get(title="elektrik_an3")
    elektrik_an4=Article.objects.get(title="elektrik_an4")
    nasilcalisiyoruz=Article.objects.get(title="nasilcalisiyoruz")
    return render(request,"elektrik.html", {"products":products,"comments":comments,"elektrik_an1":elektrik_an1,"elektrik_an2":elektrik_an2,"elektrik_an3":elektrik_an3,"elektrik_an4":elektrik_an4, "nasilcalisiyoruz":nasilcalisiyoruz })

def mekanik(request):
    
    products= Product.objects.all()
    comments = Comment.objects.all()

    mekanik_an1=Article.objects.get(title="mekanik_an1")
    mekanik_an2=Article.objects.get(title="mekanik_an2")
    mekanik_an3=Article.objects.get(title="mekanik_an3")
    mekanik_an4=Article.objects.get(title="mekanik_an4")
    nasilcalisiyoruz=Article.objects.get(title="nasilcalisiyoruz")
    return render(request,"mekanik.html", {"products":products,"comments":comments,"mekanik_an1":mekanik_an1,"mekanik_an2":mekanik_an2,"mekanik_an3":mekanik_an3,"mekanik_an4":mekanik_an4, "nasilcalisiyoruz":nasilcalisiyoruz })

def yazilim(request):
    
    products= Product.objects.all()
    comments = Comment.objects.all()

    yazilim_an1=Article.objects.get(title="yazilim_an1")
    yazilim_an2=Article.objects.get(title="yazilim_an2")
    yazilim_an3=Article.objects.get(title="yazilim_an3")
    yazilim_an4=Article.objects.get(title="yazilim_an4")
    nasilcalisiyoruz=Article.objects.get(title="nasilcalisiyoruz")
    return render(request,"yazilim.html", {"products":products,"comments":comments,"yazilim_an1":yazilim_an1,"yazilim_an2":yazilim_an2,"yazilim_an3":yazilim_an3,"yazilim_an4":yazilim_an4, "nasilcalisiyoruz":nasilcalisiyoruz })



def about(request):
    ic_ab1=Article.objects.get(title="ic_ab1")
    ic_ab2=Article.objects.get(title="ic_ab2")
    ic_ab3=Article.objects.get(title="ic_ab3")
    return render(request,"about.html",{"ic_ab1":ic_ab1,"ic_ab2":ic_ab2,"ic_ab3":ic_ab3})

@login_required
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context={
        "articles":articles
    }
    

    return render(request,"dashboard.html",context)

@login_required
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla oluşturuldu...")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    #article = Article.objects.filter(id= id).first()
    article=get_object_or_404(Article,id = id,)

    comments = article.comments.all()


    return render(request,"detail.html",{"article":article,"comments":comments},)
  
@login_required(login_url = "user:login")
def updateArticle(request,id):

    article =get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi...")
        return redirect("article:dashboard") 

    return render(request,"update.html",{"form":form})

@login_required
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()

    messages.success(request,"Makale başarıyla silnidi...")

    return redirect("article:dashboard")

def addHelp(request):
    
    
    if request.method == "POST":
        help_name = request.POST.get("name")
        help_mail = request.POST.get("email")
        help_title=request.POST.get("subject")
        help_content=request.POST.get("message")

        
        
        newHelp = help.objects.create(help_name = help_name, help_content=help_content,help_mail=help_mail,help_title=help_title)

        
        newHelp.save()


        messages.warning(request,"Mesajınız işleme alınmıştır en kısa sürede E-Posta adresinize geri dönüş sağlayacağız..")
    
    

        
            

    return redirect("contact")


def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        comment_oy=request.POST.get("rating")
        if comment_oy is None:
           messages.warning(request,"Oylama kısmı boş bırakılamaz...") 
        elif comment_content=="" or comment_author=="":
            messages.warning(request,"İsim veya yorum kısmı boş bırakılamaz..")
        else:
            bosoy=5-int(comment_oy)
            comment_script=int(comment_oy)*"<span class='fa fa-star checked'></span>"
            comment_script+=bosoy*"<span class='fa fa-star'></span>"

            newComment = Comment(comment_author = comment_author, comment_content=comment_content,comment_oy=comment_oy,comment_script=comment_script)

            newComment.article = article

            newComment.save()
            messages.warning(request,"Yorumunuz için teşekkür ederiz...")
        
    
    return redirect("index")

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Oluştur</button>
        </form>

    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-md-10 offset-md-3">
            <h3>Makaleler</h3>
            <hr>
    </div>
</div>
{% if articles %}

{% for article in articles  %}



<div class="row">
        <div class="col-md-10 offset-md-3">
        <!-- Post Content Column -->
        <div class="col-lg-8">
  
          <!-- Title -->
          <h3 class="mt-4">{{article.title}}</h3>
  
          <!-- Author -->
          <p class="lead">
            
            {{article.author.username}} tarafından yayınlandı.
          </p>
  
          <hr>
  
          <!-- Date/Time -->
          <p>{{article.created_date}}</p>
  
          <hr>
  
          <!-- Preview Image -->
          {% if article.article_image %}
          <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
          {% else %}
          {% endif %}
          
  
          <hr>
          <!-- Post Content -->
          <p class="lead">{{article.content|safe|truncatewords:10}}</p>
          <a style="float:right;" href="/articles/article/{{article.id}}" class="btn btn-danger">Devamını Oku</a>
        

          <hr>
  
          
  
          
  
          
  
        </div>
</div>
</div>

{% endfor %}

{% else %}
<div class="alert alert-danger">

    Bu blogda herhangi bir makale bulunmuyorç...

</div>
{% endif %}

{% endblock body %}

templates/contact.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="../static/img/favicon.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>İletişim</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
        <!--
        CSS
        ============================================= -->
        <link rel="stylesheet" href="../static/css/linearicons.css">
			<link rel="stylesheet" href="../static/css/font-awesome.min.css">
			<link rel="stylesheet" href="../static/css/bootstrap.css">
			<link rel="stylesheet" href="../static/css/magnific-popup.css">
			<link rel="stylesheet" href="../static/css/nice-select.css">
			<link rel="stylesheet" href="../static/css/animate.min.css">
			<link rel="stylesheet" href="../static/css/jquery-ui.css">
			<link rel="stylesheet" href="../static/css/owl.carousel.css">
			<link rel="stylesheet" href="../static/css/main.css">
    </head>
    <body>
    <div style="overflow-x: hidden;">
        <header id="header" id="home">
            <div class="header-top">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-6 col-sm-6 col-4 header-top-left no-padding">
                        <div class="menu-social-icons">
                          <a href="https://www.facebook.com/loqmah/"><i class="fa fa-facebook"></i></a>
                          <a href="https://www.instagram.com/loqmahtr/"><i class="fa fa-instagram"></i></a>

                      </div>
                        </div>

                    </div>
                </div>
          </div>
          <div class="container main-menu">
              <div class="row align-items-center justify-content-between d-flex">
                  <a href="{% url 'index'  %}"><img src="../static/img/lego.png" width="126" height="40" alt="" title="" /></a>
                  <nav id="nav-menu-container">
                      <ul class="nav-menu">
                        <li class="menu-active"><a href="{% url 'index'  %}">Anasayfa</a></li>
                        <li><a href="{% url 'about'  %}">Hakkımızda</a></li>



                        <li><a href="{% url 'contact'  %}">Bize Ulaş!</a></li>
                      </ul>
                  </nav><!-- #nav-menu-container -->
              </div>
          </div>
        </header><!-- #header -->

        <!-- start banner Area -->
        <section style="background: url({{ic_cont1.article_image.url}}) center; background-size: cover;" class="banner-area relative about-banner" id="home">
            <div  class="overlay overlay-bg"></div>
            <div class="container">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="about-content col-lg-12">
                            <div  style=" margin-bottom: 20px;"  class="container">

                                    {% if messages %}

                                        {% for message in messages %}
                                        {% if message.tags == "info" %}
                                        <div  class="alert alert-danger">{{ message }}</div>
                                        {% else %}
                                        <div  class="alert alert-{{ message.tags }}">{{ message }}</div>
                                        {% endif %}

                                        {% endfor %}

                                    {% endif %}

                                {% block body %}

                                {% endblock body %}

                            </div>
                    {{ic_cont1.content|safe}}
                    </div>
                </div>
            </div>
        </section>
        <!-- End banner Area -->

        <!-- Start contact-page Area -->
        <section class="contact-page-area section-gap">
            <div class="container">
                <div class="row">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12055.064307387891!2d29.136572892063654!3d40.94279370034445!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac42b7ae65877%3A0x7f4f6bb8110b6a71!2zUy5CLsOcIFPDvHJleXlhcGHFn2EgR8O2xJ_DvHMgSGFzdGFsxLFrbGFyxLEgdmUgR8O2xJ_DvHMgQ2VycmFoaXNpIEXEn2l0aW0gdmUgQXJhxZ90xLFybWEgSGFzdGFuZXNpIEMgQmxvaw!5e0!3m2!1str!2str!4v1579886572718!5m2!1str!2str" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

                    <div class="col-lg-4 d-flex flex-column address-wrap">
                         {{ic_cont2.content|safe}}
                    </div>
                    <div class="col-lg-8">
                        <!--<form class="form-area " id="myForm" action="{% url 'article:comment' 1 %}" method="post" class="contact-form text-right">
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <input name="name" placeholder="Adınızı ve soyadınız girin.." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required type="text">

                                    <input name="email" placeholder="E-Posta adresinizi girin.." pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required type="email">

                                    <input name="subject" placeholder="Konuyu girin.." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control" required type="text">
                                </div>
                                <div class="col-lg-6 form-group">
                                    <textarea class="common-textarea form-control" name="message" placeholder="Sizi dinliyoruz.." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required></textarea>
                                </div>
                                <div class="col-lg-12">
                                    <div class="alert-msg" style="text-align: left;"></div>
                                    <button type="submit" class="btn btn-primary">Gönder</button>
                                </div>
                            </div>
                        </form>	-->
                        <form action="{% url 'help'  %}" method="post">
                                <div class="row">
                                    <div class="col-md-6">
                                            {% csrf_token %}
                                        <div class="form-group">
                                            <label for="name">
                                                İsim Soyisim</label>
                                            <input type="text" name="name" class="form-control" id="name" placeholder="İsminizi ve soyisminizi girin" required="required" />
                                        </div>
                                        <div class="form-group">
                                            <label for="email">
                                                E-Posta</label>
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                                </span>
                                                <input name="email" type="email" class="form-control" id="email" placeholder="E-Postanızı girin" required="required" /></div>
                                        </div>
                                        <div class="form-group">
                                            <label for="subject">
                                                Konu</label>
                                                <input name="subject" type="text" class="form-control" id="subject" placeholder="Konuyu Girin" required="required" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">
                                                Mesajınız</label>
                                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                                placeholder="Sizi Dinliyoruz.."></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                                            Gönder</button>
                                    </div>
                                </div>
                                </form>

                    </div>
                </div>
            </div>
        </section>
        <!-- End contact-page Area -->

     <!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Projeniz Hazır</h6>
                    <p>
                        Unidecimal tarafından geliştirilmiştir
                    </p>
                </div>
            </div>
            <div class="col-lg-5  col-md-6 col-sm-6">
                <div class="single-footer-widget">

                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                <div class="single-footer-widget">
                    <h6>Bizi takip et</h6>
                    
                    <div class="footer-social d-flex align-items-center">
                        <a href="https://www.facebook.com//"><i class="fa fa-facebook"></i></a>
                        <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>

                    </div>
                </div>
            </div>
            <div class="col-lg-12">

                <p>unidecimal@outlook.com</p>
                <p><a href="https://www.instagram.com/unidecimal/">Unidecimal Instagram Adresi</a></p>
                <p>Copyright © 2020 Tüm Hakları Saklıdır.</p>

        </div>
    </div>
</footer>
</div>
<!-- End footer Area -->

        <script src="../static/js/vendor/jquery-2.2.4.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="../static/js/vendor/bootstrap.min.js"></script>
			<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
  			<script src="../static/js/easing.min.js"></script>
			<script src="../static/js/hoverIntent.js"></script>
			<script src="../static/js/superfish.min.js"></script>
			<script src="../static/js/jquery.ajaxchimp.min.js"></script>
			<script src="../static/js/jquery.magnific-popup.min.js"></script>
 			<script src="../static/js/jquery-ui.js"></script>
			<script src="../static/js/owl.carousel.min.js"></script>
			<script src="../static/js/jquery.nice-select.min.js"></script>
			<script src="../static/js/mail-script.js"></script>
			<script src="../static/js/main.js"></script>
    </body>
</html>

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz <small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger" href="/articles/addarticle">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
          </tr>
        </thead>
        <tbody>
            {% for article in articles  %}
                    <tr>
                    <th scope="row">{{article.id}}</th>
                    <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
                    <td>{{article.author.username}}</td>
                    <td>{{article.created_date}}</td>
                    <td><a href="/articles/update/{{article.id}}" class="btn btn-danger">Güncelle</a></td>
                    <td><a href="/articles/delete/{{article.id}}" class="btn btn-danger">Sil</a></td>
                  </tr>
            {% endfor %}
    
    
          
        </tbody>
      </table>
{% else %}
      <div class="alert alert-danger">
          Henüz bir makale yayınlamadınız..
      </div>
{% endif %}



{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
  
          <!-- Title -->
          <h3 class="mt-4">{{article.title}}</h3>
  
          <!-- Author -->
          <p class="lead">
            by
            {{article.author.username}}
          </p>
  
          <hr>
  
          <!-- Date/Time -->
          <p>{{article.created_date}}</p>
  
          <hr>
  
          <!-- Preview Image -->
          {% if article.article_image %}
          <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
          {% else %}
          {% endif %}
          
  
          <hr>
  
          <!-- Post Content -->
        {{article.content|safe}}

          <hr>
  
        {% if comments %}
        {% for comment in comments  %}
        <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.comment_author}}</h5>
              {{comment.comment_date}}<br>
              {{comment.comment_content}}
              </div>
          </div>
        {% endfor %}
        {% else %}
        <div class="alert alert-danger">
          Bu makaleye hiç yorum yapılmamış, ilk yazan siz olun!
        </div>
        {% endif %}
  
          
  
          
  
        </div>
</div>



<!-- Comments Form -->
<div class="card my-4">
    <h5 class="card-header">Yorum Yap</h5>
    <div class="card-body">
      <form method="POST" action="{% url 'article:comment' article.id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="formGroupExampleInput">İsim</label>
            <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Girin">
          </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Yorum</label>
          <textarea name="comment_content" class="form-control" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Ekle</button>
      </form>
    </div>
  </div>
        

{% endblock  %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EMC</title>
</head>
<body>
        {%include "includes/navbar.html"%}
        
        <div  style="margin-top: 100px; margin-bottom: 100px;"  class="container">

                {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div  class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div  class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endif %}
                    
                    {% endfor %}
                
                {% endif %}

            {% block body %}
            
            {% endblock body %}

        </div>



    <script src="{% static 'js/bootstrap.min.js' %}"></script>    
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>    
    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>

    </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>

    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Güncelle</button>
        </form>

    </div>
</div>
{% endblock body %}